BookPublisher/BookPublisher/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app01 import views

urlpatterns = [

    ###################删除出版社，书籍和作者整合###################
    url(r'^del_(author|publisher|book)/(\d+)/', views.delete),

    ###################出版社管理系统############################
    url(r'^publisher_system/', views.publisher_system, name='publisher'),
    url(r'^add_publisher/', views.add_publisher),
    # url(r'^del_publisher/(\d+)/', views.del_publisher),
    url(r'^edit_publisher/(\d+)/', views.edit_publisher),

    ##################图书管理系统##########################
    url(r'^book_system/', views.book_system, name='book'),
    # url(r'^add_book/', views.add_book),
    url(r'^add_book/', views.AddBook.as_view()),
    # url(r'^del_book/(\d+)/', views.del_book),

    # id通过分组命名之后，作为参数传递
    # url(r'^edit_book/', views.edit_book),
    url(r'^edit_book/(\d+)/', views.edit_book),

    #################作者管理系统#########################
    url(r'^author_system/', views.author_system, name='author'),
    url(r'^add_author/', views.add_author),
    # url(r'^del_author/(\d+)/', views.del_author),
    url(r'^edit_author/(?P<pk>\d+)/', views.edit_author),

    ######################动态路由test#############################
    # 静态路由
    url(r'^index/$', views.index),

    # 动态路由
    url(r'^index/[0-9]{3}/$', views.indexs),
    url(r'^index/[0-9]{3}$|dex[123]{2}$', views.index),  # http://127.0.0.1:8068/dex23

    # 分组命名匹配
    # 分组之后，会按照位置参数进行传参,参数个数无限制
    # 传一个参数
    url(r'^index/([0-9]{3})/$', views.years),

    # 传两个参数，只要是分组，就当作是一个参数传递
    url(r'^index/([a-z]{4})/(\d{4})/$', views.yearsmonth),

    # 分组命名之后，将捕获的参数，会按照关键字参数进行传参,参数个数无限制
    # 用分组或者命名分组看情况而定，推荐使用命名分组，名字和参数名要一样，因为是关键字参数
    # 捕获的参数都是字符串形式，路径+参数，最后匹配的还是路径
    url(r'^index/(?P<yy>[a-z]{3})/(?P<mm>\d{3})/$', views.year),

    # 再形参位置给num传递了一个默认值，这样不传递参数就用num默认值
    # 如果传入新的num值将覆盖掉num默认值，使用最新的num值
    url(r'^index2/$', views.index2),

    # http://127.0.0.1:8068/index2/page236/
    url(r'^index2/page(?P<num>[0-9]{3})/$', views.index2),  

    ######################路由分发器#######################
    # 例如我访问的路径是：http://127.0.0.1:8068/app01/blog/666/
    # 先将app01 和 url路径中的app01进行匹配，剩余的/blog/666/在app01下的路径相匹配
    # app01/ 中的/不能不加，必须加上斜杠 app01和后面的路径要拼接所以要加

    url(r'^app01/', include('app01.urls',namespace='app01')),
    url(r'^app02/', include('app02.urls',namespace='app02')),

]

BookPublisher/app01/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views

urlpatterns = [
    # 反向解析
    url(r'^index/$', views.index,name='index'),
    url(r'^index3/$', views.index3,y = 123),

    # 因为我定义了name，所以无论我的路径怎么修改，前端都能通过name去找到对应的处理函数
    # 静态路由
    url(r'^blog999995588kkk/$', views.blog, name='blog'),

    # 动态路由
    url(r'^blogs/([0-9]{3})/$', views.blogs, name='blogs'),

    # 分组命名匹配
    # 分组之后，会按照位置参数进行传参,参数个数无限制
    # 传一个参数
    # http://127.0.0.1:8068/app01/blog/666/
    url(r'^blog/([0-9]{3})/$', views.blog),

    # 传两个参数，只要是分组，就当作是一个参数传递
    # http://127.0.0.1:8068/app01/blog/abcd/8888/
    url(r'^blog/(?P<years>[a-z]{4})/(?P<months>\d{4})/$', views.blog2, name='blog2'),

    #####命名空间#########
    url(r'^home/$', views.home, name='home'),

    #特殊情况，先了解，app01下又包含了一个分发器
    # url(r'^xxxx/', include('app01.xx',namespace='xx')),

]

BookPublisher/templates/add_author.html
{% extends 'public.html' %}

{% block public %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">爱心⭐相册</h1>

        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/yichen.jpg" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan001</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/IMG_0088.JPG" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan002</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/IMG_0091.JPG" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan003</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/yidan.JPEG" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan004</h4>
                <span class="text-muted">beautiful</span>
            </div>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <p>作者：<input type="text" name="add_author"></p>
            <p>
                <select name="author_book" multiple>
                    {% for book in all_book %} {#获取book表对象#}
                        <option value="{{ book.pk }}">{{ book.title }}</option>
                    {% endfor %}
                </select>
            </p>
            <p style="color: red">{{ error }}</p>
            <button>提交</button>
        </form>
    </div>
{% endblock %}

BookPublisher/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

<form action="" method="post">
    {% csrf_token %}
    <p>图书管理系统<input type="text" name="add_book">{{ error }}</p>
    <p>
        <select name="pub_id">
            {% for pub in pub_all %}
                <option value="{{ pub.pk }}">{{ pub.name }}</option>
            {% endfor %}
        </select>
    </p>
    <p><input type="submit"></p>
</form>
</body>
</html>

BookPublisher/templates/add_publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

<form action="" method="post">
    {% csrf_token %}
    <p>出版社管理<input type="text" name="add_publisher">{{ error }}</p>
    <p><input type="submit"></p>
</form>
</body>
</html>

BookPublisher/templates/author_system.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>作者管理系统</title>

</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <table border="1">
        <thead>
        <tr>
            <th>序号</th>
            <th>作者</th>
            <th>出版书籍</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for author in all_author %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ author.name }}</td>
                <td>
                    {# author.books取得的是中间对象MangRealtedManager，再通过all方法取得book表的所有对象，再操作book表中的属性#}
                    {% for book in author.books.all %}
                        {% if forloop.last %}
                            << {{ book.title }} >>
                        {% else %}
                            << {{ book.title }} >>、
                        {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <a href="/del_author/{{ author.pk }}">删除</a>
                    <a href="/edit_author/{{ author.pk }}">编辑</a>
                </td>
            </tr>
        {% endfor %}
        <p>
            <a href="/add_author/">增加作者</a>
        </p>
        </tbody>
    </table>
</form>
</body>
</html>

BookPublisher/templates/book_system.html
{% extends 'public.html' %}
{% block book_active %}
    active
{% endblock %}

{% block publish_active %}

{% endblock %}


{% block public %}
    {% load static %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">爱心⭐相册</h1>

        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/yichen.jpg' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan001</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/IMG_0088.JPG' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan002</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/IMG_0091.JPG' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan003</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/yidan.JPEG' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan004</h4>
                <span class="text-muted">beautiful</span>
            </div>
        </div>
        {#        <h2 class="sub-header">显示信息</h2>#}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title" href="/book_system/">书籍列表</h3>
            </div>
            <div class="panel-body">
                <a href="/add_book/" class="btn btn-primary">增加书籍</a>
                {#     点击a标签就又发送了一次get请求 就会去找对应的url和地址#}
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>ID</th>
                        <th>书名</th>
                        <th>出版社名字</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    {% for book in book_all %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ book.pk }}</td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.pub.name }}</td>
                            <td>
                                <a href="/del_book/{{ book.id }}">删除</a>
{#                                <a href="{% url 'editbook' %}/{{ book.id }}/">编辑</a>#}
                                <a href="/edit_book/{{ book.id }}/">编辑</a>
                            </td>
                        </tr>
                    {% empty %}
                        <td>没有相关的数据</td>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

BookPublisher/templates/edit_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">
    {% csrf_token %}
    {#value是默认在输入框中的书名#}
    <p>作者管理系统<input type="text" name="edit_author" value='{{ edit_author.name }}'></p>
    <select name="authod_id" multiple>
        {% for book in book_all %}
            {#循环遍历所有的出版社对象，出版社的对象和当前的book出的对象是同一个，说明是一个对象，选成默认的就可以#}
            {% if book in edit_author.books.all %}
                {#这是一个下拉列表框，此句只表示默认选中，也就是for循环中的对象都会走到#}
                <option selected value="{{ book.pk }}">{{ book.title }}</option>
            {% else %}
                <option value="{{ book.pk }}">{{ book.title }}</option>
            {% endif %}
        {% endfor %}
    </select>
    <p style="color: red">{{ error }}</p>
    <p><input type="submit"></p>
</form>
</body>
</html>

BookPublisher/templates/edit_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">
    {% csrf_token %}
    {#value是默认在输入框中的书名#}
    <p>图书管理系统<input type="text" name="edit_book" value='{{ edit.title }}'>{{ error }}</p>
    <select name="edit_publisher">
        {% for pub in pub_all %}
            {#循环遍历所有的出版社对象，出版社的对象和当前的book出的对象是同一个，说明是一个对象，选成默认的就可以#}
            {% if edit.pub == pub %}
                {#这是一个下拉列表框，此句只表示默认选中，也就是for循环中的对象都会走到#}
                <option selected value="{{ pub.pk }}">{{ pub.name }}</option>
            {% else %}
                <option value="{{ pub.pk }}">{{ pub.name }}</option>
            {% endif %}
        {% endfor %}
    </select>
    <p><input type="submit"></p>
</form>
</body>
</html>

BookPublisher/templates/edit_publisher.html
{% extends 'public.html' %}

{% block public %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">爱心⭐相册</h1>

        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/yichen.jpg" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan001</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/IMG_0088.JPG" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan002</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/IMG_0091.JPG" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan003</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="/static/img/yidan.JPEG" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan004</h4>
                <span class="text-muted">beautiful</span>
            </div>
        </div>
        <h2 class="sub-header">显示信息</h2>
        <form action="" method="post">
            {% csrf_token %}
            <p>出版社管理<input type="text" name="edit_publisher" value='{{ edit.name }}'>{{ error }}</p>
            <p><input type="submit"></p>

        </form>
    </div>
{% endblock %}

BookPublisher/templates/index3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#这个标签就可以获取原本的url地址，也就是通过name找到url地址，就是反向解析#}
<a href="{% url 'app01:blog' %}">博客</a>

<a href="{% url 'app01:blogs' 123 %}">博客s</a>

<a href="{% url 'app01:blog2' years='abcd' months=8888 %}">博客s2</a>

<a href="{% url 'app02:home' %}">博客home</a>

{#特殊情况先了解#}
{#<a href="{% url 'app01:xxx:index' %}"></a>#}
</body>
</html>

BookPublisher/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

BookPublisher/templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分页显示</title>
    {# 使用静态文件#}
    {% load static %}
    <link rel="stylesheet" href="{% static '/plugins/bootstrap-3.3.7/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/dsb.css' %}">
</head>
<body>
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for i in num %}
            <li><a href="">{{ i }}</a> </li>
        {% endfor %}
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
</body>
</html>

BookPublisher/templates/public.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {# 使用静态文件#}
    {% load static %}
    <link rel="stylesheet" href="{% static '/plugins/bootstrap-3.3.7/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/dsb.css' %}">
</head>
<body>
{# 使用组件 #}
{% include 'nav.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class=" {% block publish_active %}active{% endblock %}"><a href="/publisher_system/">出版社列表 <span
                        class="sr-only">(current)</span></a></li>
                <li class="{% block book_active %}{% endblock %}"><a href="/book_system/">书籍列表 <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
        {% block public %}

        {% endblock %}
    </div>
</div>
</body>
</html>

BookPublisher/templates/publisher_system.html
{% extends 'public.html' %}

{% block public %}
    {% load static %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">爱心⭐相册</h1>

        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/yichen.jpg' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan001</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/IMG_0088.JPG' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan002</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/IMG_0091.JPG' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan003</h4>
                <span class="text-muted">beautiful</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="{% static '/img/yidan.JPEG' %}" width="200" height="200" class="img-responsive"
                     alt="Generic placeholder thumbnail">
                <h4>Mrs.dan004</h4>
                <span class="text-muted">beautiful</span>
            </div>
        </div>
        {#        <h2 class="sub-header">显示信息</h2>#}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title" href="/publisher_system/">出版社列表</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        {#                    <th>ID</th>#}
                        <th>出版社</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for publish in all_publisher %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {#                <td>{{ publish.pid }}</td>#}
                            <td>{{ publish.name }}</td>
                            <td>
                                <a href="/del_publisher/{{ publish.pid }}">删除</a>
                                <a href="/edit_publisher/{{ publish.pid }}">编辑</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <a href="/add_publisher/" class="btn btn-primary">增加出版社</a>
                </table>
            </div>
        </div>
        {% load my_tags %}
        {% page 10 %}
{##}
{#        {% load my_tags %}#}
{#        {% sqr_list 3 %}#}
    </div>

{% endblock %}